markdown: redcarpet
highlighter: pygments # or rouge or null

title: Lumbr
tagline: This is the tagline
email: seth@coelen.co


timezone: America/New_York
excerpt_separator: <!--more-->
exclude: ["node_modules", "gulpfile.js", "package.json"]




