name: fun time
markdown: redcarpet
highlighter: pygments # or rouge or null
timezone: America/New_York
copyright: © copyright 2015 - YourSiteName.com
excerpt_separator: <!--more-->
exclude: ["node_modules", "gulpfile.js", "package.json"]




